const produtosFake = [
    {
        id: 3,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: false,
    },
    {
        id: 1,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: false,
    },
    {
        id: 4,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: false,
    },
    {
        id: 5,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: false,
    },
    {
        id: 6,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: true,
    },
    {
        id: 7,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: false,
    },
    {
        id: 8,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: false,
    },
    {
        id: 9,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: false,
    },
    {
        id: 10,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: true,
    },
    {
        id: 11,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: true,
    },
    {
        id: 12,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: "100",
        precoAntes: "...",
        precoDepois: "...",
        ativo: false,
    },
    {
        id: 13,
        nome: "...",
        categoria: "...",
        descricao: "...",
        desconto: 0,
        precoAntes: "...",
        precoDepois: "...",
        ativo: true,
    },
];

export default produtosFake;
